#!/usr/bin/python3

DBUS_PROPERTIES_INTERFACE = "org.freedesktop.DBus.Properties"
DBUS_OBJECT_MANAGER_INTERFACE = "org.freedesktop.DBus.ObjectManager"

BLUEZ_ADAPTER_NAME = "hci0"

BLUEZ_SERVICE_NAME = "org.bluez"
BLUEZ_NAMESPACE = "/org/bluez"

BLUEZ_ADAPTER_INTERFACE = BLUEZ_SERVICE_NAME + ".Adapter1"
BLUEZ_DEVICE_INTERFACE = BLUEZ_SERVICE_NAME + ".Device1"
BLUEZ_GATT_MANAGER_INTERFACE = BLUEZ_SERVICE_NAME + ".GattManager1"
BLUEZ_GATT_SERVICE_INTERFACE = BLUEZ_SERVICE_NAME + ".GattService1"
BLUEZ_GATT_CHARACTERISTIC_INTERFACE = BLUEZ_SERVICE_NAME + ".GattCharacteristic1"
BLUEZ_GATT_DESCRIPTOR_INTERFACE = BLUEZ_SERVICE_NAME + ".GattDescriptor1"
BLUEZ_ADVERTISEMENT_INTERFACE = BLUEZ_SERVICE_NAME + ".LEAdvertisement1"
BLUEZ_ADVERTISING_MANAGER_INTERFACE = BLUEZ_SERVICE_NAME + ".LEAdvertisingManager1"
BLUEZ_AGENT_MANAGER_INTERFACE = BLUEZ_SERVICE_NAME + ".AgentManager1"
BLUEZ_AGENT_INTERFACE = BLUEZ_SERVICE_NAME + ".Agent1"

RESULT_OK = 0
RESULT_ERR = 1
RESULT_ERR_NOT_CONNECTED = 2
RESULT_ERR_NOT_SUPPORTED = 3
RESULT_ERR_SERVICES_NOT_RESOLVED = 4	
RESULT_ERR_WRONG_STATE = 5
RESULT_ERR_ACCESS_DENIED = 6
RESULT_EXCEPTION = 7
RESULT_ERR_BAD_ARGS = 8
RESULT_ERR_NOT_FOUND = 9

